return {
    "Aesop and the Ferryman",
    "Hercules and the Wagoner",
    "Horkos, the god of oaths",
    "Momus criticizes the creations of the gods",
    "The Ant and the Grasshopper",
    "The Ape and the Fox",
    "The Ass Carrying an Image",
    "The Ass and his Masters",
    "The Ass and the Pig",
    "The Ass in the Lion's Skin",
    "The Astrologer who Fell into a Well",
    "The Bald Man and the Fly",
    "The Bear and the Travelers",
    "The Beaver",
    "The Belly and the Other Members",
    "The Bird in Borrowed Feathers",
    "The Bird-catcher and the Blackbird",
    "The Boy Who Cried Wolf",
    "The Cat and the Mice",
    "The Cock and the Jewel",
    "The Cock, the Dog and the Fox",
    "The Crab and the Fox",
    "The Crow and the Pitcher",
    "The Crow and the Sheep",
    "The Crow and the Snake",
    "The Deer without a Heart",
    "The Dog and its Reflection",
    "The Dog and the Sheep",
    "The Dog and the Wolf",
    "The Dove and the Ant",
    "The Eagle Wounded by an Arrow",
    "The Eagle and the Beetle",
    "The Eagle and the Fox",
    "The Farmer and his Sons",
    "The Farmer and the Sea",
    "The Farmer and the Stork",
    "The Farmer and the Viper",
    "The Fir and the Bramble",
    "The Fisherman and his Flute",
    "The Fisherman and the Little Fish",
    "The Fly and the Ant",
    "The Fly in the Soup",
    "The Fowler and the Snake",
    "The Fox and the Crow",
    "The Fox and the Grapes",
    "The Fox and the Lion",
    "The Fox and the Mask",
    "The Fox and the Sick Lion",
    "The Fox and the Stork",
    "The Fox and the Weasel",
    "The Fox and the Woodman",
    "The Fox, the Flies and the Hedgehog",
    "The Frightened Hares",
    "The Frog and the Mouse",
    "The Frog and the Ox",
    "The Frogs Who Desired a King",
    "The Frogs and the Sun",
    "The Goat and the Vine",
    "The Goose that Laid the Golden Eggs",
    "The Hare in flight",
    "The Honest Woodcutter",
    "The Horse and the Donkey",
    "The Horse that Lost its Liberty",
    "The Impertinent Insect",
    "The Jar of Blessings",
    "The Kite and the Doves",
    "The Lion Grown Old",
    "The Lion and the Mouse",
    "The Lion in Love",
    "The Lion's Share",
    "The Lion, the Bear and the Fox",
    "The Man and the Lion",
    "The Man with two Mistresses",
    "The Mischievous Dog",
    "The Miser and his Gold",
    "The Mountain in Labour",
    "The Mouse and the Oyster",
    "The North Wind and the Sun",
    "The Oak and the Reed",
    "The Old Man and Death",
    "The Old Man and his Sons",
    "The Old Man and the Ass",
    "The Old Woman and the Doctor",
    "The Old Woman and the Wine-jar",
    "The Oxen and the Creaking Cart",
    "The Rivers and the Sea",
    "The Rose and the Amaranth",
    "The Satyr and the Traveller",
    "The Shipwrecked Man and the Sea",
    "The Sick Kite",
    "The Snake and the Crab",
    "The Snake and the Farmer",
    "The Snake in the Thorn Bush",
    "The Statue of Hermes",
    "The Swan and the Goose",
    "The Tortoise and the Birds",
    "The Tortoise and the Hare",
    "The Town Mouse and the Country Mouse",
    "The Travellers and the Plane Tree",
    "The Trees and the Bramble",
    "The Trumpeter Taken Captive",
    "The Two Pots",
    "The Walnut Tree",
    "The Wolf and the Crane",
    "The Wolf and the Lamb",
    "The Wolf and the Shepherds",
    "The Woodcutter and the Trees",
    "The Young Man and the Swallow",
    "The dogs and the lion's skin",
    "The lion, the boar and the vultures",
    "Venus and the Cat",
    "War and his Bride",
    "Washing the Ethiopian white",
    "Zeus and the Tortoise"
}
